spring:
  application:
    name: gateway-server
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**,/api/admin/users/**,/api/users/**,/users/**

        - id: BOOKING-SERVICE
          uri:
            lb://BOOKING-SERVICE
          predicates:
            - Path=/api/bookings/**

        - id: PAYMENT-SERVICE
          uri:
            lb://PAYMENT-SERVICE
          predicates:
              - Path=/api/payments/**

        - id: CATEGORY-SERVICE
          uri:
            lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/categories/**

        - id: SALON-SERVICE
          uri:
            lb://SALON-SERVICE
          predicates:
            - Path=/salons/**,/api/salons/**,/api/admin/salons/**

        - id: SERVICE-OFFERING
          uri:
            lb://SERVICE-OFFERING
          predicates:
            - Path=/api/service-offering/**

        - id: NOTIFICATION-SERVICE
          uri:
            lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"




server:
  port: 5007




eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"