server:
  port: 5008

spring:
  application:
    name: notification-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/notificationdb?createDatabaseIfNotExist=true
    username: root
    password: root
  rabbitmq:
    port: 5672
    host: rabbit
    username: guest
    password: guest

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"


