server:
  port: 5008

spring:
  application:
    name: notification-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:notificationdb}:3306/notificationdb?createDatabaseIfNotExist=true
    username: root
    password: root

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: "http://eurekaserver:8070/eureka/"