spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:bookingdb}:3306/bookingdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 5005

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: "http://eurekaserver:8070/eureka/"