spring:
  application:
    name: payment-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:paymentdb}:3306/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: root

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

stripe:
  api:
    key: STRIPE_API_KEY

razorpay:
  api:
    key: RAZOR_PAY_API
    secret: RAZOR_PAY_SECRET

server:
  port: 5006

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: "http://eurekaserver:8070/eureka/"