spring:
  application:
    name: payment-service
  config:
    import: "optional:env:.env"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/paymentdb?createDatabaseIfNotExist=true
    username: root
    password: root

stripe:
  api:
    key: ${STRIPE_API_KEY:default_stripe_key}

razorpay:
  api:
    key: ${RAZORPAY_API_KEY:default_razorpay_key}
    secret: ${RAZORPAY_API_SECRET:default_razorpay_secret}

server:
  port: 5006

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"