spring.application.name=payment-service
server.port=5006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/paymentdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

stripe.api.key=${STRIPE_API_KEY}
razorpay.api.key=${RAZORPAY_API_KEY}
razorpay.api.secret=${RAZORPAY_API_SECRET}