server:
  port: 5010

spring:
  application:
    name: ai-service
  ai:
    google:
      api-key: YOUR_GEMINI_API_KEY

      chat:
        model: gemini-1.5-flash


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hairstyledb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  codec:
    max-in-memory-size: 10MB

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"
