spring:
  application:
    name: service-offering

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:service-offeringdb}:3306/service-offeringdb
    username: root
    password: root

server:
  port: 5004

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: "http://eurekaserver:8070/eureka/"