spring:
  application:
    name: salon-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:salondb}:3306/salondb
    username: root
    password: root

server:
  port: 5002

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

    service-url:
      defaultZone: "http://eurekaserver:8070/eureka/"